#version: "3.9"
services:
  proxy:
    container_name: openvimai
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    volumes:
      - ./server:/app/server
      - ./logs:/app/logs
    ports:
      - "8000:8000"
    restart: unless-stopped
